/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/mfa-methods/retrieve": {
    /**
     * Retrieves the list of MFA Methods for a user
     * @description Retrieve mfaMethods that match criteria in the MFASearchRequest in the request body
     */
    post: operations["mfa-methods-retrieve"];
  };
  "/mfa-methods": {
    /** @description Creates an mfa method. A new MFA Method cannot be created as PRIMARY, it must be SECONDARY and promoted at a later stage */
    post: operations["mfa-method-create"];
  };
  "/mfa-methods/{mfaIdentifier}": {
    /** @description Updates an mfa method. If the MFA method is updated to 'PRIMARY', the current 'PRIMARY' gets relegated to secondary. */
    put: operations["mfa-methods-update"];
    /** @description Deletes the mfa method identified by the mfa identifier. Cannot delete an identifier that is 'PRIMARY'. */
    delete: operations["mfa-method-delete"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @enum {string} */
    PriorityEnum: "DEFAULT" | "BACKUP";
    /** @enum {string} */
    MethodTypeEnum: "SMS" | "AUTH_APP";
    MfaMethod: {
      mfaIdentifier?: number;
      priorityIdentifier: components["schemas"]["PriorityEnum"];
      method:
        | components["schemas"]["SmsMethod"]
        | components["schemas"]["AuthAppMethod"];
      methodVerified?: boolean;
      smsPhoneNumber?: string;
    };
    SmsMethod: {
      /** @enum {string} */
      mfaMethodType?: "SMS";
      phoneNumber?: string;
    };
    /**
     * @example {
     *   "priorityIdentifier": "DEFAULT",
     *   "mfaMethodType": "SMS",
     *   "phoneNumber": "070"
     * }
     */
    AuthAppMethod: {
      /** @enum {string} */
      mfaMethodType?: "AUTH_APP";
      credential?: string;
    };
    /**
     * @example {
     *   "priorityIdentifier": "DEFAULT",
     *   "mfaMethodType": "AUTH_APP",
     *   "credential": "AAAABBBBCCCCCDDDDD55551111EEEE2222FFFF3333GGGG4444"
     * }
     */
    MfaMethodCreate: {
      priorityIdentifier: components["schemas"]["PriorityEnum"];
      mfaMethodType: components["schemas"]["MethodTypeEnum"];
      endPoint?: string;
      credential?: string;
    };
    /**
     * @example {
     *   "mfaIdentifier": 1,
     *   "priorityIdentifier": "DEFAULT",
     *   "mfaMethodType": "SMS",
     *   "endPoint": "070"
     * }
     */
    MfaMethodUpdate: {
      mfaIdentifier: number;
      priorityIdentifier: components["schemas"]["PriorityEnum"];
      mfaMethodType: components["schemas"]["MethodTypeEnum"];
      credential?: string;
      endPoint?: string;
    };
    /**
     * @example {
     *   "email": "testusersearching@searchersexampledomain.co.uk"
     * }
     */
    MfaSearchRequest: {
      email: string;
    };
    /**
     * @example {
     *   "email": "testuser@testexampledomain.co.uk",
     *   "credential": "???",
     *   "otp": "123456",
     *   "mfaMethod": {
     *     "priorityIdentifier": "DEFAULT",
     *     "mfaMethodType": "AUTH_APP",
     *     "endPoint": "n/a"
     *   },
     *   "methodVerified": true
     * }
     */
    MfaMethodCreateRequest: {
      email: string;
      credential: string;
      otp: string;
      mfaMethod: components["schemas"]["MfaMethodCreate"];
    };
    /**
     * @example {
     *   "email": "testuser@testexampledomain.co.uk",
     *   "otp": "123456",
     *   "mfaMethod": {
     *     "mfaIdentifier": 1,
     *     "priorityIdentifier": "DEFAULT",
     *     "mfaMethodType": "AUTH_APP",
     *     "endPoint": "n/a"
     *   }
     * }
     */
    MfaMethodUpdateRequest: {
      email: string;
      otp: string;
      mfaMethod: components["schemas"]["MfaMethodUpdate"];
    };
    ProblemDetail: {
      /**
       * Format: uri
       * @example https://account.gov.uk/problems/mfa-method-not-updated
       */
      type?: string;
      /** @example MFA Method could not be updated. */
      title?: string;
      status?: string;
      /** @example Database error */
      detail?: string;
      /** @example /mfa-methods/{mfaIdentifier} */
      resource?: string;
      extension?: {
        error?: {
          /** @enum {unknown} */
          code?: 1056 | 1057 | 1058;
        };
      };
    };
    ValidationProblem: {
      type?: string;
      title?: string;
      errors?: components["schemas"]["Error"][];
    };
    Error: {
      detail?: string;
      pointer?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Retrieves the list of MFA Methods for a user
   * @description Retrieve mfaMethods that match criteria in the MFASearchRequest in the request body
   */
  "mfa-methods-retrieve": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MfaSearchRequest"];
      };
    };
    responses: {
      /** @description Successful Operation.  The retrieve query was accepted and the response contains all matching MFAMethods. */
      200: {
        content: {
          "application/json": components["schemas"]["MfaMethod"][];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ValidationProblem"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description Search not available */
      500: {
        content: {
          "application/json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  /** @description Creates an mfa method. A new MFA Method cannot be created as PRIMARY, it must be SECONDARY and promoted at a later stage */
  "mfa-method-create": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MfaMethodCreateRequest"];
      };
    };
    responses: {
      /** @description MFA Method Created */
      200: {
        content: {
          "application/json": components["schemas"]["MfaMethod"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description MFA Method could not be created */
      500: {
        content: {
          "application/json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  /** @description Updates an mfa method. If the MFA method is updated to 'PRIMARY', the current 'PRIMARY' gets relegated to secondary. */
  "mfa-methods-update": {
    parameters: {
      path: {
        mfaIdentifier: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MfaMethodUpdateRequest"];
      };
    };
    responses: {
      /** @description MFA Method Updated */
      200: {
        content: {
          "application/json": components["schemas"]["MfaMethod"];
        };
      };
      /** @description MFA Method not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description MFA Method could not be updated */
      500: {
        content: {
          "application/json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  /** @description Deletes the mfa method identified by the mfa identifier. Cannot delete an identifier that is 'PRIMARY'. */
  "mfa-method-delete": {
    parameters: {
      path: {
        mfaIdentifier: string;
      };
    };
    responses: {
      /** @description MFA Method Deleted */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description MFA Method Not found */
      404: {
        content: {
          "application/json": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description Cannot delete a Primary MFA Method */
      409: {
        content: {
          "application/json": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description MFA Method could not be deleted */
      500: {
        content: {
          "application/json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
}
