name: Checkov

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@d9d1e5cdc53e3a91f0c4c58db7bc19ee31cac7e5 
        with:
          file: template.yaml
          framework: cloudformation
          # CKV_AWS_116 - Lambda functions should have a Dead Letter Queue configured not required for stub functions
          # CKV_AWS_28 - Lambda functions should have reserved concurrency configured not required for stub functions
          skip_check: CKV_AWS_28,CKV_AWS_116 
          output_format: cli
          output_file_path: console
