name: Checkov

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@7b972723c44fb3d256283fac96fae5d7c1894bb7 
        with:
          file: template.yaml
          framework: cloudformation
          # CKV_AWS_116 - Lambda functions should have a Dead Letter Queue configured not required for stub functions
          # CKV_AWS_28 - Lambda functions should have reserved concurrency configured not required for stub functions
          skip_check: CKV_AWS_28,CKV_AWS_116 
          output_format: cli
          output_file_path: console
